[build]
  command = "npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# FormSubmit integration - same setup as RMT Solutions
# Emails sent directly to info@comfortlivingrealestate.com
# No configuration needed - zero setup required